### ISSUE TITLE
Add get started on terminal: "pip install permon; permon -terminal"

### ISSUE THREAD

**Issue by tx1985** [bminixhofer/permon#15]
I had to search for how to use permon in the terminal. It would have helped me if there was a two-liner, titled "Get started" at the Readme or Documentation, which says:

```
pip install permon
permon -terminal
```

This was not apparent for me.

Edit: The command `permon terminal` did not work on my Ubuntu 16.04, not sure if that was actually intended, or not.

**Comment by bminixhofer** [comment]
Hi, thanks for pointing this out. 
The documentation was made for 2.0.0 but it is not fully correct at the moment because version 2.0.0 is not released yet. The only issue still blocking this is #9 so I expect to be done very soon.
In the meantime, try 
`pip install git+https://www.github.com/bminixhofer/permon`. That will install version 2.0.0 which is already release-ready on all systems but MacOS.
I will also add the commands needed to get started right away to the Introduction and Readme.

**Comment by bminixhofer** [comment]
Permon 2.0.0 is now on PyPI!
The behavior is now exactly the one described in the documentaion.
Try running `pip install --upgrade permon` and `permon terminal` to use version 2.0.0.

As you suggested, I have also added a Quickstart section to the readme. The essential commands to get started are listed there now.
